/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IDEAPAD GAMING
 */
public class DataGantiRugiView extends javax.swing.JPanel {

    /**
     * Creates new form DataBukuView
     */
    Connection koneksi;
    Statement kalimat;

    private final String dbUrl = "jdbc:mysql://localhost/perpustakaan";
    private final String user = "root";
    private final String pass = "";
    String select = "SELECT * FROM `buku_dibayar`";
    LocalDate today = LocalDate.now();
    LocalDate pinjam = LocalDate.now();
    LocalDate kembali = LocalDate.now();
    
    public DataGantiRugiView() {
        initComponents();
        loadData();
    }

    public void loadData() {
    try {
        koneksi = DriverManager.getConnection(dbUrl, user, pass);
        kalimat = koneksi.createStatement();
        ResultSet resultSet = kalimat.executeQuery(select);
        DefaultTableModel model = (DefaultTableModel) tabel_databuku.getModel();
        model.setRowCount(0);
        while (resultSet.next()) {
            LocalDate pinjam = LocalDate.now();
            java.sql.Date sqlDateKembali = resultSet.getDate("tanggal_kembali");
                
            LocalDate tanggalKembali = sqlDateKembali != null ? sqlDateKembali.toLocalDate() : null;
                
                // Hitung keterlambatan
            String terlambat = "Tidak terlambat";
            if (tanggalKembali != null) {
                long daysBetween = ChronoUnit.DAYS.between(pinjam, tanggalKembali);
                long daysLate = ChronoUnit.DAYS.between(tanggalKembali, pinjam);
                if (daysBetween < 0 ) {
                    terlambat = "Terlambat " + (daysLate) + " hari";
                }
            }
            model.addRow(new Object[]{
                resultSet.getString("id"),
                resultSet.getString("judul"),
                resultSet.getString("nim"),
                resultSet.getString("nama"),
                resultSet.getString("tanggal_pinjam"),
                resultSet.getString("tanggal_kembali"),
                terlambat,
                resultSet.getString("denda"),
                resultSet.getString("ganti_rugi"),
                resultSet.getString("total"),
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Panel = new javax.swing.JPanel();
        Panel_bukuhilang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_databuku = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_search = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        Main_Panel.setLayout(new java.awt.CardLayout());

        Panel_bukuhilang.setBackground(new java.awt.Color(255, 255, 255));

        tabel_databuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N0", "Judul", "NIM", "Nama Peminjam", "Tanggal Pinjam", "Tanggal Kembali", "Terlambat", "Denda", "Ganti Rugi Buku", "Total"
            }
        ));
        tabel_databuku.setGridColor(new java.awt.Color(0, 102, 51));
        tabel_databuku.setSelectionBackground(new java.awt.Color(0, 102, 51));
        tabel_databuku.setSelectionForeground(new java.awt.Color(0, 102, 51));
        tabel_databuku.setShowGrid(true);
        jScrollPane1.setViewportView(tabel_databuku);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        jLabel1.setText("Data Ganti Rugi Buku");

        jSeparator1.setBackground(new java.awt.Color(0, 102, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 51));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N

        jSeparator3.setBackground(new java.awt.Color(0, 102, 51));
        jSeparator3.setForeground(new java.awt.Color(0, 102, 51));

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_search.setText("Search");
        txt_search.setBorder(null);

        javax.swing.GroupLayout Panel_bukuhilangLayout = new javax.swing.GroupLayout(Panel_bukuhilang);
        Panel_bukuhilang.setLayout(Panel_bukuhilangLayout);
        Panel_bukuhilangLayout.setHorizontalGroup(
            Panel_bukuhilangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_bukuhilangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_bukuhilangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_bukuhilangLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_bukuhilangLayout.createSequentialGroup()
                        .addGap(249, 410, Short.MAX_VALUE)
                        .addGroup(Panel_bukuhilangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_bukuhilangLayout.createSequentialGroup()
                                .addComponent(txt_search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        Panel_bukuhilangLayout.setVerticalGroup(
            Panel_bukuhilangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_bukuhilangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(Panel_bukuhilangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_bukuhilangLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );

        Main_Panel.add(Panel_bukuhilang, "card2");

        add(Main_Panel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JPanel Panel_bukuhilang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tabel_databuku;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
